import {
  Config,
  Layout,
  Widget,
  WidgetStyle,
  buildBorder,
  createDefaultWidgetStyle,
} from '../schema';
import { createLayoutRow } from './layout';

export interface Preset {
  id: string;
  name: string;
  layout: Partial<Layout>;
}

/**
 * 黑夜 · 雾夜青
 * 主色：墨蓝灰底 + 薄荷绿强调
 * 辅色：雾蓝标题 / 青→天蓝进度 / 浅青数值
 */
export const baseStyle = createDefaultWidgetStyle({
  color: '#e4eef2',
  font: 'inherit',
  fontSize: 13,
  bold: false,
  italic: false,
  labelBold: false,
  bg: 'transparent',
  bgOpacity: 1,
  colorOpacity: 1,
  align: 'left',
  alignV: 'center',
  radius: 8,
  padding: 5,
  barMax: 100,
  barColor: '#6ebfb0',
  barColorEnd: '#8ec5d8',
  barTrack: '#252d38',
  barTrackOpacity: 0.92,
  barHeight: 12,
  barValueMode: 'outside',
  barValueColor: '#b4c9d2',
  barValueFontSize: 11,
  labelColor: '#94aab4',
  labelFontSize: 12,
  labelAlign: 'left',
  labelAlignV: 'center',
  groupBorder: false,
  chipEnabled: false,
  chipBorder: 'rgba(126, 201, 184, 0.42)',
  chipBg: 'rgba(126, 201, 184, 0.1)',
  fieldsGap: 6,
  width: 'auto',
  span: 1,
  direction: 'row',
  fieldsLayout: 'stack',
  stackAccent: '',
  stackFontSize: 11,
  stackShowTabs: true,
  stackGap: 4,
  stackTabRadius: 12,
  stackTabPadY: 0,
  stackTabTrack: 'rgba(126, 201, 184, 0.12)',
  stackTabColor: '#a8bcc6',
  stackTabInactiveBg: 'transparent',
  stackTabActiveColor: '#7ec9b8',
  stackTabActiveBg: 'rgba(126, 201, 184, 0.2)',
  stackTabLabelMode: 'tab',
  imgMode: 'cover',
  imgWidth: '100%',
  imgHeight: 'auto',
  imgRadius: 8,
  imgStretch: false,
});

/** 分隔线默认：上下间距尽量紧，可用「内边距」再调 */
export const dividerStylePatch: Partial<WidgetStyle> = {
  padding: 0,
  bg: 'transparent',
};

/**
 * 白天 · 晨雾桃青
 * 主色：雾白绿底 + 青绿强调
 * 辅色：鼠尾草绿标题 / 青→蜜桃进度 / 深青绿数值
 */
export const dayWidgetStyle = createDefaultWidgetStyle({
  color: '#2c4a42',
  font: 'inherit',
  fontSize: 13,
  bold: false,
  italic: false,
  labelBold: false,
  bg: 'transparent',
  bgOpacity: 1,
  colorOpacity: 1,
  align: 'left',
  alignV: 'center',
  radius: 9,
  padding: 5,
  barMax: 100,
  barColor: '#5fad9c',
  barColorEnd: '#e8b4a0',
  barTrack: '#e4f0eb',
  barTrackOpacity: 1,
  barHeight: 12,
  barValueMode: 'outside',
  barValueColor: '#4a7a6e',
  barValueFontSize: 11,
  labelColor: '#6b8f86',
  labelFontSize: 12,
  labelAlign: 'left',
  labelAlignV: 'center',
  groupBorder: false,
  chipEnabled: false,
  chipBorder: 'rgba(95, 173, 156, 0.4)',
  chipBg: 'rgba(95, 173, 156, 0.09)',
  fieldsGap: 6,
  width: 'auto',
  span: 1,
  direction: 'row',
  fieldsLayout: 'stack',
  stackAccent: '',
  stackFontSize: 11,
  stackShowTabs: true,
  stackGap: 4,
  stackTabRadius: 12,
  stackTabPadY: 0,
  stackTabTrack: 'rgba(95, 173, 156, 0.1)',
  stackTabColor: '#6b8f86',
  stackTabInactiveBg: 'transparent',
  stackTabActiveColor: '#3d8a7a',
  stackTabActiveBg: 'rgba(95, 173, 156, 0.18)',
  stackTabLabelMode: 'tab',
  imgMode: 'cover',
  imgWidth: '100%',
  imgHeight: 'auto',
  imgRadius: 8,
  imgStretch: false,
});

/** 内置预设：黑夜 / 白天各一套完整可调字段 */
export const PRESETS: Preset[] = [
  {
    id: 'night',
    name: '黑夜',
    layout: {
      bg: '#161c24',
      bgOpacity: 1,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#3a4d5c',
      border: '1px solid #3a4d5c',
      radius: 14,
      fontFamily: 'inherit',
      textColor: '#e4eef2',
      textOpacity: 1,
      accentColor: '#7ec9b8',
      scrollbarColor: 'rgba(126, 201, 184, 0.42)',
      scrollbarHoverColor: 'rgba(142, 197, 216, 0.72)',
      editorRangeTrack: 'rgba(94, 170, 184, 0.28)',
      editorRangeThumb: '#7ec9b8',
      editorRangeThumbHover: '#8ec5d8',
      padding: 12,
      gap: 8,
      columns: 2,
      widgetDefaults: { ...baseStyle },
      themeDefaults: { ...baseStyle },
    },
  },
  {
    id: 'day',
    name: '白天',
    layout: {
      bg: '#f5f9f7',
      bgOpacity: 1,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#c5ddd4',
      border: '1px solid #c5ddd4',
      radius: 16,
      fontFamily: 'inherit',
      textColor: '#2c4a42',
      textOpacity: 1,
      accentColor: '#5fad9c',
      scrollbarColor: 'rgba(95, 173, 156, 0.4)',
      scrollbarHoverColor: 'rgba(232, 180, 160, 0.72)',
      editorRangeTrack: 'rgba(107, 143, 134, 0.22)',
      editorRangeThumb: '#5fad9c',
      editorRangeThumbHover: '#e8b4a0',
      padding: 14,
      gap: 10,
      columns: 2,
      widgetDefaults: { ...dayWidgetStyle },
      themeDefaults: { ...dayWidgetStyle },
    },
  },
];

/** 默认初始配置：黑夜 · 雾夜青 */
export function defaultConfig(): Config {
  const widgets: Widget[] = [
    {
      id: 'w1',
      type: 'label',
      source: 'static',
      binding: {
        mvu_parent: '',
        mvu_field: '',
        mvu_fields: [],
        db_table: '',
        db_row: 1,
        db_column: '',
        db_columns: [],
        static_value: '自定义状态栏',
      },
      name: '',
      label: '',
      children: [],
      rows: [],
      collapsed: false,
      activePageIndex: 0,
      autoRotateMs: 0,
      dbAutoRows: false,
      dbTabColumn: '',
      dbRowFilter: '',
      imageMatchField: false,
      imageMap: [],
      style: {
        ...baseStyle,
        fontSize: 16,
        bold: true,
        align: 'center',
        width: '100%',
        span: 1,
        direction: 'column',
        color: '#eef6f8',
      },
    },
    {
      id: 'w2',
      type: 'kv',
      source: 'static',
      binding: {
        mvu_parent: '',
        mvu_field: '',
        mvu_fields: [],
        db_table: '',
        db_row: 1,
        db_column: '',
        db_columns: [],
        static_value: '示例值',
      },
      name: '',
      label: '示例',
      children: [],
      rows: [],
      collapsed: false,
      activePageIndex: 0,
      autoRotateMs: 0,
      dbAutoRows: false,
      dbTabColumn: '',
      dbRowFilter: '',
      imageMatchField: false,
      imageMap: [],
      style: { ...baseStyle },
    },
  ];
  const border = buildBorder(1, 'solid', '#3a4d5c');
  return {
    layout: {
      columns: 2,
      gap: 8,
      padding: 12,
      bg: '#161c24',
      bgOpacity: 1,
      border,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#3a4d5c',
      radius: 14,
      fontFamily: 'inherit',
      textColor: '#e4eef2',
      textOpacity: 1,
      accentColor: '#7ec9b8',
      scrollbarColor: 'rgba(126, 201, 184, 0.42)',
      scrollbarHoverColor: 'rgba(142, 197, 216, 0.72)',
      editorRangeTrack: 'rgba(94, 170, 184, 0.28)',
      editorRangeThumb: '#7ec9b8',
      editorRangeThumbHover: '#8ec5d8',
      widgetDefaults: { ...baseStyle },
      themeDefaults: { ...baseStyle },
      rows: [
        createLayoutRow({ columns: 1, widgetIds: ['w1'] }),
        createLayoutRow({ columns: 1, widgetIds: ['w2'] }),
      ],
    },
    widgets,
  };
}
